apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qiwhra0as-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qiwhra0as-java-quarkus-gitops